version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.4
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run: node --version
      - heroku/install
      - run:
          command: >
            npm test
          name: Running tests
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - deploy
