version: 2.1
jobs:
  deploy:
    executor: heroku/default
    docker:
      - image: cimg/node:14.4
    steps:
      - checkout
      - run: node --version
      - run: npm install
      - run: npm test
      - heroku/install
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - deploy
